apiVersion: v1
kind: Pod
metadata:
  name: custom-metrics-collector
spec:
  restartPolicy: Never
  serviceAccountName: metrics-sa
  containers:
    - name: busybox
      image: busybox:stable
      command: ['sh', '-c', 'while true; do echo Running...; sleep 5; done']
