apiVersion: v1
kind: Pod
metadata:
  name: ps-backend
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: busybox:stable
      command: ['sh', '-c', 'echo $LOG_LEVEL; echo $DB_HOST; echo $DB_PORT']
      env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: log_level
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: db_host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: db_port