apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: config
      mountPath: "/etc/nginx/conf.d"
  volumes:
  - name: config
    configMap:
      name: nginx-config