apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-role-binding
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin-role
subjects:
- kind: Group
  name: kadmin
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: sjackson
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: klink
  apiGroup: rbac.authorization.k8s.io