apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: node-maintenance-cluster-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-maintenance
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: cluster-ops
