apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: readonly-config-secrets
  namespace: ps-dev
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs: ["get", "watch", "list"]
