apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: readonly-config-secrets-role-bindings
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: readonly-config-secrets
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: developers
