apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ps-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secrets-viewer-role
subjects:
- kind: ServiceAccount
  name: ps-sa
  namespace: dev
