apiVersion: v1
kind: Pod
metadata:
  name: cache-pod
spec:
  containers:
  - name: busybox
    image: busybox:stable
    command: ['sh', '-c', 'while true; do echo Running...; sleep 5; done']
    volumeMounts:
    - mountPath: /var/cache
      name: cache-volume
    securityContext:
      runAsUser: 4050
      runAsGroup: 4050
      capabilities:
        drop: ["SYS_TIME"]
      readOnlyRootFilesystem: true
  volumes:
    - name: cache-volume
      emptyDir: {}
