apiVersion: v1
kind: Pod
metadata:
  name: file-svc
spec:
  securityContext:
    runAsUser: 1005
    runAsGroup: 4007
    runAsNonRoot: true
    fsGroup: 800
    fsGroupChangePolicy: "OnRootMismatch"
  containers:
  - name: busybox
    image: busybox:stable
    command: ['sh', '-c', 'while true; do echo Running...; sleep 5; done']