apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
spec:
  containers:
  - name: busybox
    image: busybox:stable
    command: ['sh', '-c', 'while true; do echo Running...; sleep 5; done']
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true
      capabilities:
        drop: ["CAP_NET_BIND_SERVICE"]