apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: flags.pluralsight.com
spec:
  group: pluralsight.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                new_ui:
                  type: boolean
                beta:
                  type: boolean
  scope: Namespaced
  names:
    plural: flags
    singular: flag
    kind: Flag
    shortNames:
      - fl
