apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: autoscalers.pluralsight.com
spec:
  group: pluralsight.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cpuThresholdPercent:
                  type: integer
                memoryThresholdPercent:
                  type: integer
  scope: Namespaced
  names:
    plural: autoscalers
    singular: autoscaler
    kind: AutoScaler
    shortNames:
      - as
